---
title: "Assessment Report"
subtitle: "`r data$Data$Metadata$Value[data$Data$Metadata$Field=='Fishery']`"
date: "`r ifelse(is.null(data$Data$Metadata$Value[data$Data$Metadata$Field=='Date']) | is.na(data$Data$Metadata$Value[data$Data$Metadata$Field=='Date']), Sys.Date(), data$Data$Metadata$Value[data$Data$Metadata$Field=='Date'])`"
---
<style type="text/css">
h1 { /* Header 1 */
  font-size: 24px;
}
</style>
```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

tab.num <<- fig.num <<- 0

fig.number <- function() {
  fig.num <<- fig.num + 1
  paste0('Figure ', fig.num, '.')
}
  
tab.number <- function() {
  tab.num <<- tab.num + 1
  paste0('Table ', tab.num , '.')
}
  

```


# {.tabset}
## Fishery Information

```{r}
knitr::kable(data$Data$Metadata, caption=paste(tab.number(), 'Fishery Information.'))
```

## At-Age Schedules 

```{r}
 weight_at_age <- report_weight_at_age(data$Data)
 colnames(weight_at_age$df)[3:4] <- c('10th', '90th')

 # Maturity-at-Age
 maturity_at_age <- report_maturity_at_age(data$Data)

 # M-at-Age
 M_at_age <- report_M_at_age(data$Data)

 # PSM-at-Age
 PSM <- report_PSM_at_age(data$Data)

 df <- dplyr::left_join(weight_at_age$df, maturity_at_age$df, by='Age')
 df <- dplyr::left_join(df, M_at_age$df, by='Age')
 df <- dplyr::left_join(df, PSM$df, by='Age')
 
```


```{r, fig.cap=paste(fig.number(), 'a) The mean weight-at-age, with 10th and 90th percentiles., b) The natural mortality-at-age schedule. c) The maturity-at-age schedule. d)The post-spawning mortality-at-age schedule.')}
plot_at_Age(data$Data)
```

```{r}
 knitr::kable(df, caption=paste(tab.number(), 'Table of values for the At-Age schedules.'))
```


## Data {.tabset}

### Catch-at-Weight

```{r, fig.width=8,fig.height=16, fig.cap=paste(fig.number(), 'The catch-at-weight data with the model fit shown as a blue line. Each plot is standardised to sum to 1 across the weight classes. The sample size is shown in the top left corner.')}
 CAW <- plot_CAW(data)
 CAW$p
```


### Indices 

```{r fig.cap=paste(fig.number(), 'a) The indices of vulnerable biomass, b) effort, and c) catch, with 10 and 90th percentiles. The blue dashed line indicates the model fit. Empty plots mean no data was provided.'), fig.height=8}
plot_Indices(data)
```


## Assessment Results {.tabset}

### Tables 

```{r}
knitr::kable(assumed_pars(data),  caption=paste(tab.number(), 'Assumed parameters used in the assessment.'))
```

```{r}
DT::datatable(report_NLL(data),  caption=paste(tab.number(), 'Negative log-likelihood values.'),
                options = list(
    info = FALSE,
    paging = FALSE,
    searching = FALSE
  ))
```


```{r}
df <- make_df(data) %>% select(Year, Month, SPR, F, log_rec_devs) %>% 
  dplyr::mutate(dplyr::across(3:5, \(x) round(x,3)))

DT::datatable(df,  caption=paste(tab.number(), 'Estimated values.'),
                options = list(
    info = FALSE,
    paging = FALSE,
    searching = FALSE
  ))

```

### Seasonal Recruitment Pattern 
```{r, fig.cap=paste(fig.number(), 'The estimated seasonal recruitment pattern.')}
p <- plot_seasonal_rec(data)
p$p

```

### Selectivity

```{r, fig.cap=paste(fig.number(), 'The estimated selectivity pattern.')}
p <- plot_selectivity(data)
p$p
```


### Time-Series

```{r, fig.cap=paste(fig.number(), 'The estimated spawning potential ratio.')}
plot_SPR(data)
```

```{r, fig.cap=paste(fig.number(), 'The estimated fishing mortality.')}
plot_F(data)
```

### Reference Points 
```{r, fig.cap=paste(fig.number(), 'The mean monthly F and SPR (red lines) and the optimal values calculated from the HARA utility model with two values for the exponent (rows). Lower values of the HARA exponent mean higher utility for lower variance in catches throughout the year. Higher values of the HARA exponent mean greater utilty on the overall annual catch.')}
plot_RP(data)
```




