---
title: "Data Report"
subtitle: "`r data$Data$Metadata$Value[data$Data$Metadata$Field=='Fishery']`"
date: "`r ifelse(is.null(data$Data$Metadata$Value[data$Data$Metadata$Field=='Date']) | is.na(data$Data$Metadata$Value[data$Data$Metadata$Field=='Date']), Sys.Date(), data$Data$Metadata$Value[data$Data$Metadata$Field=='Date'])`"
---
<style type="text/css">
h1 { /* Header 1 */
  font-size: 24px;
}
</style>
```{r setup2, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

tab.num <<- fig.num <<- 0

fig.number <- function() {
  fig.num <<- fig.num + 1
  paste0('Figure ', fig.num, '.')
}
  
tab.number <- function() {
  tab.num <<- tab.num + 1
  paste0('Table ', tab.num , '.')
}
  


```


# {.tabset}
## Fishery Information

```{r}
knitr::kable(data$Metadata, caption=paste(tab.number(), 'Fishery Information.'))
```

## At-Age Schedules 

```{r}
 weight_at_age <- plot_weight_at_age(data)
 colnames(weight_at_age$df)[3:4] <- c('10th', '90th')

 # Maturity-at-Age
 maturity_at_age <- plot_maturity_at_age(data)

 # M-at-Age
 M_at_age <- plot_M_at_age(data)

 # PSM-at-Age
 PSM <- plot_M_at_age(data)

 df <- dplyr::left_join(weight_at_age$df, maturity_at_age$df, by='Age')
 df <- dplyr::left_join(df, M_at_age$df, by='Age')
 df <- dplyr::left_join(df, PSM$df, by='Age')
 
```

```{r, fig.cap=paste(fig.number(), 'a) The mean weight-at-age, with 10th and 90th percentiles., b) The natural mortality-at-age schedule. c) The maturity-at-age schedule. d)The post-spawning mortality-at-age schedule.')}
plot_at_Age(data)
```

```{r}
 knitr::kable(df, caption=paste(tab.number(), 'Table of values for the At-Age schedules.'))
```


## Data {.tabset}

### Catch-at-Weight

```{r, fig.width=8,fig.height=16, fig.cap=paste(fig.number(), 'The catch-at-weight data. Each plot is standardised to sum to 1 across the weight classes. The sample size is shown in the top left corner.')}
 CAW <- plot_CAW(data)
 CAW$p
```

### Indices 

```{r fig.cap=paste(fig.number(), 'a) The indices of vulnerable biomass, b) effort, and c) catch, with 10 and 90th percentiles. Empty plots mean no data was provided.'), fig.height=8}
plot_Indices(data)
```


